"""add_relationships_and_fix_nullable

Revision ID: 094f32878e8e
Revises: 837d1fdcce77
Create Date: 2026-04-12 06:23:06.879598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094f32878e8e'
down_revision: Union[str, Sequence[str], None] = '837d1fdcce77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
