"""add_notifications_table

Revision ID: 81ef51e140d5
Revises: e08a97e8fd5c
Create Date: 2026-04-20 08:50:08.941907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ef51e140d5'
down_revision: Union[str, Sequence[str], None] = 'e08a97e8fd5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constituencies', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constituencies', 'view_count')
    # ### end Alembic commands ###
