"""add_constituency_to_user

Revision ID: e08a97e8fd5c
Revises: 215b12e80e5d
Create Date: 2026-04-20 07:52:31.691214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08a97e8fd5c'
down_revision: Union[str, Sequence[str], None] = '215b12e80e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('constituency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'constituencies', ['constituency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'constituency_id')
    # ### end Alembic commands ###
